<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <link rel="stylesheet" href="css/styles.css">
    <title>Ajouter un logement</title>
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container">
                <a class="navbar-brand" href="index.php">Accueil</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link" href="add_logement.php">Ajouter un logement</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <main class="container">
        <!-- Messages d'erreurs -->
        <?php if (isset($errors) && !empty($errors)) : ?>
            <?php foreach ($errors as $error) : ?>
                <p class="alert alert-danger m-2"><?= $error; ?></p>
            <?php endforeach; ?>
        <?php endif; ?>

        <!-- Formulaire d'ajout de logement -->
        <h1 class="text-center h2 mt-3 text-warning">Ajouter un logement</h1>
        <form action="add_logement.php" method="POST" class="mb-5">
            <div class="mb-3">
                <label for="titre" class="form-label">Titre</label>
                <input required type="text" class="form-control" id="titre" name="titre" value="<?php if (isset($_POST['titre'])): ?><?= htmlspecialchars($_POST['titre']); ?><?php endif; ?>">
            </div>
            <div class="mb-3">
                <label for="adresse" class="form-label">Adresse</label>
                <input required type="text" class="form-control" id="adresse" name="adresse" value="<?php if (isset($_POST['adresse'])): ?><?= htmlspecialchars($_POST['adresse']); ?><?php endif; ?>">
            </div>
            <div class="mb-3">
                <label for="ville" class="form-label">Ville</label>
                <input required type="text" class="form-control" id="ville" name="ville" value="<?php if (isset($_POST['ville'])): ?><?= htmlspecialchars($_POST['ville']); ?><?php endif; ?>">
            </div>
            <div class="mb-3">
                <label for="cp" class="form-label">Code postal</label>
                <input required type="number" class="form-control" id="cp" name="cp" value="<?php if (isset($_POST['cp'])): ?><?= htmlspecialchars($_POST['cp']); ?><?php endif; ?>">
            </div>
            <div class="mb-3">
                <label for="surface" class="form-label">Surface</label>
                <input required type="number" min="0" class="form-control" id="surface" name="surface" value="<?php if (isset($_POST['surface'])): ?><?= htmlspecialchars($_POST['surface']); ?><?php endif; ?>">
            </div>
            <div class="mb-3">
                <label for="prix" class="form-label">Prix</label>
                <input required type="number" min="0" class="form-control" id="prix" name="prix" value="<?php if (isset($_POST['prix'])): ?><?= intval($_POST['prix']); ?><?php endif; ?>">
            </div>
            <div class="mb-3">
                <label for="photo" class="form-label">Photo</label>
                <input type="text" class="form-control" id="photo" name="photo" value="<?php if (isset($_POST['photo'])): ?><?= htmlspecialchars($_POST['photo']); ?><?php endif; ?>">
            </div>
            <div class="mb-3">
                <label class="form-label" for="type">Type</label>
                <select class="form-select" id="type" name="type">
                    <option>Location</option>
                    <option>Vente</option>
                </select>
            </div>
            <div class="mb-3">
                <label for="description" class="form-label">Description</label>
                <textarea type="number" class="form-control" id="description" name="description"><?php if (isset($_POST['description'])): ?><?= htmlspecialchars($_POST['description']); ?><?php endif; ?></textarea>
            </div>
            <div class="d-grid gap-2">
                <button type="submit" class="btn btn-warning btn-block">Ajouter</button>
            </div>
        </form>
    </main>

    <footer class="py-5 bg-dark">
        <div class="container">
            <p class="m-0 text-center text-white">© 2020 - Samuel Compte</p>
        </div>
    </footer>


    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
</body>

</html>