<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <link rel="stylesheet" href="css/styles.css">
    <title>Page d'accueil</title>
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container">
                <a class="navbar-brand" href="index.php">Accueil</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link" href="add_logement.php">Ajouter un logement</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <main class="container">
        <h1 class="text-center h2 mt-3 text-warning mb-5">Logement n°<?= intval($logement['id_logement']); ?></h1>
        <img src="images/<?= htmlspecialchars($logement['photo']); ?>" alt="" class="d-block mx-auto w-75">
        <div class="text-center">
            <h2 class="mt-3"><?= htmlspecialchars($logement['titre']); ?></h2>
            <p class="mb-0"><span class="fw-bold">Adresse : </span><?= htmlspecialchars($logement['adresse']); ?></p>
            <p class="mb-0"><span class="fw-bold">Ville : </span><?= htmlspecialchars($logement['ville']); ?></p>
            <p class="mb-0"><span class="fw-bold">Code postal : </span><?= htmlspecialchars($logement['cp']); ?></p>
            <p class="mb-0"><span class="fw-bold">Surface : </span><?= htmlspecialchars($logement['surface']); ?> m²</p>
            <p class="mb-0"><span class="fw-bold">Type : </span><?= htmlspecialchars($logement['type']); ?></p>
            <p class="mb-0"><span class="fw-bold">
                    Prix : </span><?= format_price($logement['prix']); ?>
                <?php if ($logement['type'] == 'Location') : ?>
                    / Mois
                <?php endif; ?>
            </p>
            <p class="w-50 mx-auto"><?= nl2br(htmlspecialchars($logement['description'])); ?></p>
        </div>
    </main>

    <footer class="py-5 bg-dark">
        <div class="container">
            <p class="m-0 text-center text-white">© 2020 - Samuel Compte</p>
        </div>
    </footer>


    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
</body>

</html>