<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <link rel="stylesheet" href="css/styles.css">
    <title>Page d'accueil</title>
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container">
                <a class="navbar-brand" href="index.php">Accueil</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link" href="add_logement.php">Ajouter un logement</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <main class="container">
        <h1 class="text-center h2 mt-3 text-warning mb-5">Bienvenue sur la page d'accueil</h1>
        <section class="row">
            <!-- Affichage des logements -->
            <?php foreach ($logements as $logement) : ?>
                <div class="col-md-4 mb-4">
                    <div class="card" style="width: 18rem;">
                        <img src="images/<?= htmlspecialchars($logement['photo']); ?>" class="card-img-top" alt="...">
                        <div class="card-body">
                            <h5 class="card-title"><?= htmlspecialchars($logement['titre']); ?></h5>
                            <p class="card-text fw-bold mb-0"><?= format_price($logement['prix']); ?></p>
                            <p class="card-text fw-bold mb-0"><?= htmlspecialchars($logement['ville']); ?></p>
                            <p class="card-text mb-0"><?= htmlspecialchars(substr($logement['description'], 0, 60)); ?>...</p>
                            <p class="card-text badge bg-success"><?= htmlspecialchars($logement['type']); ?></p>
                            <a href="detail_logement.php?id=<?= intval($logement['id_logement']); ?>" class="btn btn-warning d-block">Voir le détail</a>
                        </div>
                    </div>
                </div>
            <?php endforeach; ?>
        </section>
    </main>

    <footer class="py-5 bg-dark">
        <div class="container">
            <p class="m-0 text-center text-white">© 2020 - Samuel Compte</p>
        </div>
    </footer>


    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
</body>

</html>